//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjTelefones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_telefone
    {
        public int id { get; set; }
        public string numero { get; set; }
        public string tipo { get; set; }
        public int id_pessoa { get; set; }
    
        public virtual tb_pessoa tb_pessoa { get; set; }
    }
}
